### ISSUE TITLE
custom base path

### ISSUE THREAD

**Issue by cjunekim** [kometenstaub/obsidian-version-history-diff#9]
Hi

This plugin doesn't seem to work with custom base path feature of Obsidian Git plugin. When it is set to a child folder and it is ran by Show Git Diff View command, it results in an error.

![image](https://user-images.githubusercontent.com/9114235/167854240-ea67469f-f270-4930-92e7-df6cda486cf6.png)

In my case, the child folder name is Subfolder and the custom base path option is set as such.

![image](https://user-images.githubusercontent.com/9114235/167854644-00858c12-93a0-4b62-9890-645290cf0e74.png)

**Comment by kometenstaub** [comment]
@Vinzent03 
I think that‘s something you would need to implement in the Git plugin API.

**Comment by Vinzent03** [comment]
@cjunekim Is `Subfolder` directly below your vault? E.g `desktop/myVault/Subfolder`?

**Comment by cjunekim** [comment]
> @cjunekim Is `Subfolder` directly below your vault? E.g `desktop/myVault/Subfolder`?

Yes.

**Comment by Vinzent03** [comment]
Hmm tricky.
@kometenstaub Am I right that you use only `show`, `log`, `diff`?

**Comment by cjunekim** [comment]
Ping. How is this going?

**Comment by kometenstaub** [comment]
> Hmm tricky. @kometenstaub Am I right that you use only `show`, `log`, `diff`?

Only `log` and `show`. I don't use `diff` because the base implementation works on file contents that get diffed with `jsdiff` and not commit hashes.

**Comment by kometenstaub** [comment]
@Vinzent03 I think I don't use anything else, unless I've overlooked something.

https://github.com/kometenstaub/obsidian-version-history-diff/blob/main/src/git_diff_view.ts

**Comment by Vinzent03** [comment]
@cjunekim Can you try updating Obsidian-Git. The issue should be fixed.

**Comment by cjunekim** [comment]
@Vinzent03 I still get an error as following:

```
plugin:obsidian-git:7354 Uncaught (in promise) Error: fatal: ambiguous argument 'A 사용법.md': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Object.action (plugin:obsidian-git:10679:25)
    at PluginStore.exec (plugin:obsidian-git:10704:25)
    at eval (plugin:obsidian-git:8499:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:8497:16)
    at GitExecutorChain.eval (plugin:obsidian-git:8481:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:7333:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Something notable to me is the file name 'A 사용법.md' is not the full filename. The first character is cut out. It was originally 'AA 사용법.md'(without the single quote).

**Comment by Vinzent03** [comment]
@cjunekim Your git root folder is still `Subfolder` without any slashes at the start or end? And your file path relative to your vault is `Subfolder/AA 사용법.md`?

**Comment by cjunekim** [comment]
> @cjunekim Your git root folder is still `Subfolder` without any slashes at the start or end? And your file path relative to your vault is `Subfolder/AA 사용법.md`?

Oh. I got it. The Custom base path (Git repository path) was set to "/Subfolder". I removed the slash at the front, and it seems to work now. Maybe there is some mishandling of slash in the filename. Thanks!

**Comment by Vinzent03** [comment]
Maybe I should check/correct wrong formatting.
@kometenstaub I think this can be closed now.

**Comment by kometenstaub** [comment]
> @kometenstaub I think this can be closed now.

Thanks!

**Comment by cjunekim** [comment]
Oh my goodness! Recently, I had to clean install obsidian and git on a new computer and clone the repository.

This time I didn't use the custom base path. Thus, I use the git root as the vault directory. However, the same error happens.

> fatal: ambiguous argument 'A 사용법.md': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

The first character of the filename is removed.
